Namespace(lr=0.0001, lr_backbone=1e-05, batch_size=1, weight_decay=0.0001, epochs=1, lr_drop=200, clip_max_norm=0.1, save_freq=5, benchmark=False, append_word=None, backbone='resnet50', dilation=False, position_embedding='sine', layer1_frozen=False, layer2_frozen=False, frozen_weights='', resume='', no_opt=False, LETRpost=False, layer1_num=3, layer2_num=2, enc_layers=6, dec_layers=6, dim_feedforward=2048, hidden_dim=256, dropout=0.1, nheads=8, num_queries=1000, pre_norm=False, second_enc_layers=6, second_dec_layers=6, second_dim_feedforward=2048, second_hidden_dim=256, second_dropout=0.1, second_nheads=8, second_pre_norm=False, aux_loss=True, set_cost_class=1, set_cost_line=5, set_cost_point=5, dice_loss_coef=1, point_loss_coef=5, line_loss_coef=5, eos_coef=0.1, label_loss_func='cross_entropy', label_loss_params='{}', dataset_file='coco', coco_path='dataset_marco', coco_panoptic_path=None, remove_difficult=False, output_dir='', device='cpu', seed=42, start_epoch=0, num_workers=2, num_gpus=1, world_size=1, dist_url='env://', eval=False, dataset='train', distributed=False)
Device :  cpu
number of params: 41509895
building coco dataset
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
building coco dataset
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
NO RESUME. TRAIN FROM SCRATCH
Start training
Start training at epoch:  0
Total epochs:  1
DataloaderTrain :  1
/home/alexis/miniconda3/envs/deepl/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/alexis/LETR_euler/src/main.py", line 231, in <module>
    main(args)
  File "/home/alexis/LETR_euler/src/main.py", line 192, in main
    train_stats = train_one_epoch(model, criterion, postprocessors, data_loader_train, optimizer, device, epoch, args.clip_max_norm, args)
  File "/home/alexis/LETR_euler/src/engine.py", line 30, in train_one_epoch
    for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/home/alexis/LETR_euler/src/util/misc.py", line 219, in log_every
    for obj in iterable:
  File "/home/alexis/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/alexis/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/alexis/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/alexis/.local/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/alexis/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/alexis/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/alexis/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/alexis/LETR_euler/src/datasets/coco.py", line 22, in __getitem__
    img, target = super(CocoDetection, self).__getitem__(idx)
  File "/home/alexis/miniconda3/envs/deepl/lib/python3.10/site-packages/torchvision/datasets/coco.py", line 48, in __getitem__
    image = self._load_image(id)
  File "/home/alexis/miniconda3/envs/deepl/lib/python3.10/site-packages/torchvision/datasets/coco.py", line 41, in _load_image
    return Image.open(os.path.join(self.root, path)).convert("RGB")
  File "/home/alexis/miniconda3/envs/deepl/lib/python3.10/site-packages/PIL/Image.py", line 3131, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'dataset_marco/train/ai_001_001/images/scene_cam_00_final_preview/frame.0000.color.jpg'